main: me.wittybit.PlayerShop.Main
name: PlayerShop
version: "0.2.17a"
author: AgathokakologicalBit
api-version: "1.16"

commands:
  account:
    description: Allows player to access the information about owned account
  transfer:
    description: Transfers specified amount of money to the target player
  setbalance:
    description: Changes the account balance of a chosen player
  tradeit:
    description: Creates a new trade request with offer being a currently held item
  trades:
    description: shows the list of available trade requests
